using System;using System.IO;using System.Collections.Generic;using System.Web.Script.Serialization;
public static class CombinedTests
{
 public static void Run(string root)
 {
  string discord=Path.Combine(root,"Discord.exe"),game=Path.Combine(root,"Game.exe");File.WriteAllText(discord,"fixture");File.WriteAllText(game,"fixture");var r=new EngineRequest{PermanentDiscord=true,Host="192.0.2.20",Port=6000,User="game-user",Password="game-secret",OwnerPath=Path.Combine(root,"owner.exe"),Route=new RoutingOptions(),DiscordOverlay=new DiscordProfile{Host="192.0.2.30",Port=7000,User="discord-user",Password="discord-secret",DiscordPath=discord}};r.Route.Apps.Add(new RegisteredApp{Path=game});r.Route.Apps.Add(new RegisteredApp{Path=discord});
  foreach(bool global in new[]{false,true}){r.Route.Global=global;string json=TunConfiguration.Build(r);var config=(Dictionary<string,object>)new JavaScriptSerializer().DeserializeObject(json);var outputs=(object[])config["outbounds"];if(outputs.Length!=3)throw new Exception("Missing separate proxy");if((string)((Dictionary<string,object>)outputs[0])["server"]!="192.0.2.20"||(string)((Dictionary<string,object>)outputs[2])["server"]!="192.0.2.30")throw new Exception("Proxy configuration mixed");var routing=(Dictionary<string,object>)config["route"];var rules=(object[])routing["rules"];if((string)((Dictionary<string,object>)rules[2])["outbound"]!="discord-proxy"||(string)((Dictionary<string,object>)rules[3])["outbound"]!="direct"||(string)((Dictionary<string,object>)rules[4])["action"]!="reject")throw new Exception("Discord precedence lost");File.WriteAllText(Path.Combine(root,global?"combined-global.json":"combined-apps.json"),json);}
  r.Route.Global=false;r.Protocol="HTTPS";File.WriteAllText(Path.Combine(root,"combined-https.json"),TunConfiguration.Build(r));r.PermanentDiscord=false;bool rejected=false;try{TunConfiguration.Build(r);}catch(ArgumentException){rejected=true;}if(!rejected)throw new Exception("Overlay without permanent host accepted");Console.WriteLine("PASS: separate Discord/Dashboard proxies, Discord precedence in global and per-app routes, HTTPS Dashboard coexistence, invalid overlay rejection.");
 }
}
